common/models/Industry.php
<?php
namespace common\models;

use Yii;


class Industry extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'industries';
    }

    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    public function attributeLabels()
    {
        return [
           'name' => 'Industry Name',

        ];
    }



}

backend/controllers/IndustriesController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Industry;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\data\ActiveDataProvider;

/**
 * ChatController implements the CRUD actions for Chat model.
 */
class IndustriesController extends Controller
{

    public function actionIndex()
    {

        $industries = Industry::find()->all();

        return $this->render('index', ['model' => $industries]);
    }

  public function actionCreate()
    {
        $model = new Industry();
        // new record
        if($model->load(Yii::$app->request->post()) && $model->validate()){
          if ($model->save()) {
              return $this->redirect(['index']);
          }
        }

        return $this->render('create', ['model' => $model]);
    }

     /**
     * Edit
     * @param integer $id
     */
    public function actionEdit($id)
    {
        $model = Industry::find()->where(['id' => $id])->one();

        // $id not found in database
        if($model === null)
            throw new NotFoundHttpException('The requested page does not exist.');

        // update record
        if($model->load(Yii::$app->request->post()) && $model->validate()){
          if ($model->save()) {
              return $this->redirect(['index']);
          }
        }

        return $this->render('update', ['model' => $model]);
    }


    /**
     * Delete
     * @param integer $id
     */
     public function actionDelete($id)
     {
         $model = Industry::findOne($id);

        // $id not found in database
        if($model === null)
            throw new NotFoundHttpException('The requested page does not exist.');

        // delete record
        $model->delete();

        return $this->redirect(['index']);
     }





}

backend/views/industries/_form.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\datepicker\DatePicker;
use dosamigos\ckeditor\CKEditor;
use kartik\time\TimePicker;
use frontend\models\User;


/* @var $this yii\web\View */
/* @var $model common\models\Chat */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="chat-form">

    <?php $form = ActiveForm::begin([
        'options' => ['enctype' => 'multipart/form-data'],
    ]); ?>

        <?= $form->field($model, 'name')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/industries/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Chat */

$this->title = 'Create Industry';
$this->params['breadcrumbs'][] = ['label' => 'Industry', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="chat-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/industries/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\Edition;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\ChatSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Industries';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="chat-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Industry', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

      <table border="1" class="table table-striped table-bordered">
    <tr>
        <th>#</th>
        <th>Industry Name</th>
        <th>Actions</th>
    </tr>
    <?php foreach($model as $field){ ?>
    <tr>
        <td><?= $field->id; ?></td>
        <td><?= $field->name; ?></td>
        <td><?= Html::a("Edit", ['industries/edit', 'id' => $field->id]); ?> | <?= Html::a("Delete", ['industries/delete', 'id' => $field->id]); ?></td>
    </tr>
    <?php } ?>
</table>
</div>

backend/views/industries/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Chat */

$this->title = 'Update Industry: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Industry', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="chat-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>