backend/models/Slider.php
<?php
namespace backend\models;

use Yii;
use common\models\Chat;

class Slider extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'top_sliders';
    }

    public function rules()
    {
        return [
            
            [['slider_1', 'slider_2', 'slider_3','slider_4','slider_5','slider_6'], 'string', 'max' => 255]
        ];
    }

    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
           'slider_1' => 'Slider 1',
           'slider_2' => 'Slider 2',
           'slider_3' => 'Slider 3',
           'slider_4' => 'Slider 4',
           'slider_5' => 'Slider 5',
           'slider_6' => 'Slider 6',
        ];
    }
    /**
     * @inheritdoc
     */
    // public function rules()
    // {
    //     return [
    //        [['Chat','AnswersID','Question_1', 'Question_2'], 'required'],
    //         [['Question_1', 'Question_2','Question_3','Question_4','Question_5'], 'string', 'max' => 255]


    //     ];
    // }



}

backend/controllers/SliderController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Slider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use common\models\Reviews;
use yii\data\ActiveDataProvider;

/**
 * ChatController implements the CRUD actions for Chat model.
 */
class SliderController extends Controller
{

    public function actionIndex()
    {

        $slider = Slider::find()->all();

        return $this->render('index', ['model' => $slider]);
    }

  public function actionCreate()
    {
        $model = new Slider();
        $uploadPath = \Yii::getAlias('@frontend/web/sliders');
        // new record
        if($model->load(Yii::$app->request->post()) && $model->validate()){
          $slider1 = UploadedFile::getInstance($model, 'slider_1');
          $slider2 = UploadedFile::getInstance($model, 'slider_2');
          $slider3 = UploadedFile::getInstance($model, 'slider_3');
          $slider4 = UploadedFile::getInstance($model, 'slider_4');
          $slider5 = UploadedFile::getInstance($model, 'slider_5');
          $slider6 = UploadedFile::getInstance($model, 'slider_6');
          if (!empty($slider1)) {
              $slider_1 =  uniqid() . preg_replace('/\s+/', '_', $slider1->name);
              if ($slider1->saveAs($uploadPath . '/' . $slider1->name)) {
                  $model->slider_1= $slider1->name;
              }
          }
          if (!empty($slider2)) {
              if ($slider2->saveAs($uploadPath . '/' . $slider2->name)) {
                  $model->slider_2= $slider2->name;
              }
          }
          if (!empty($slider3)) {
              $slider_3 =  uniqid() . preg_replace('/\s+/', '_', $slider3->name);
              if ($slider3->saveAs($uploadPath . '/' . $slider3->name)) {
                  $model->slider_3= $slider3->name;
              }
          }
          if (!empty($slider4)) {
              $slider_4 =  uniqid() . preg_replace('/\s+/', '_', $slider4->name);
              if ($slider4->saveAs($uploadPath . '/' . $slider4->name)) {
                  $model->slider_4= $slider4->name;
              }
          }
          if (!empty($slider5)) {
              $slider_5 =  uniqid() . preg_replace('/\s+/', '_', $slider5->name);
              if ($slider5->saveAs($uploadPath . '/' . $slider5->name)) {
                  $model->slider_5= $slider5->name;
              }
          }
          if (!empty($slider6)) {
              $slider_6 =  uniqid() . preg_replace('/\s+/', '_', $slider6->name);
              if ($slider6->saveAs($uploadPath . '/' . $slider6->name)) {
                  $model->slider_6= $slider6->name;
              }
          }
          if ($model->save()) {
              return $this->redirect(['index']);
          }
        }

        return $this->render('create', ['model' => $model]);
    }

     /**
     * Edit
     * @param integer $id
     */
    public function actionEdit($id)
    {
        $model = Slider::find()->where(['id' => $id])->one();
        $uploadPath = \Yii::getAlias('@frontend/web/sliders');

        // $id not found in database
        if($model === null)
            throw new NotFoundHttpException('The requested page does not exist.');

        // update record
        if($model->load(Yii::$app->request->post()) && $model->validate()){
          $slider1 = UploadedFile::getInstance($model, 'slider_1');
          $slider2 = UploadedFile::getInstance($model, 'slider_2');
          $slider3 = UploadedFile::getInstance($model, 'slider_3');
          $slider4 = UploadedFile::getInstance($model, 'slider_4');
          $slider5 = UploadedFile::getInstance($model, 'slider_5');
          $slider6 = UploadedFile::getInstance($model, 'slider_6');
          if (!empty($slider1)) {
              $slider_1 =  uniqid() . preg_replace('/\s+/', '_', $slider1->name);
              if ($slider1->saveAs($uploadPath . '/' . $slider1->name)) {
                  $model->slider_1= $slider1->name;
              }
          }
          if (!empty($slider2)) {
              if ($slider2->saveAs($uploadPath . '/' . $slider2->name)) {
                  $model->slider_2= $slider2->name;
              }
          }
          if (!empty($slider3)) {
              $slider_3 =  uniqid() . preg_replace('/\s+/', '_', $slider3->name);
              if ($slider3->saveAs($uploadPath . '/' . $slider3->name)) {
                  $model->slider_3= $slider3->name;
              }
          }
          if (!empty($slider4)) {
              $slider_4 =  uniqid() . preg_replace('/\s+/', '_', $slider4->name);
              if ($slider4->saveAs($uploadPath . '/' . $slider4->name)) {
                  $model->slider_4= $slider4->name;
              }
          }
          if (!empty($slider5)) {
              $slider_5 =  uniqid() . preg_replace('/\s+/', '_', $slider5->name);
              if ($slider5->saveAs($uploadPath . '/' . $slider5->name)) {
                  $model->slider_5= $slider5->name;
              }
          }
          if (!empty($slider6)) {
              $slider_6 =  uniqid() . preg_replace('/\s+/', '_', $slider6->name);
              if ($slider6->saveAs($uploadPath . '/' . $slider6->name)) {
                  $model->slider_6= $slider6->name;
              }
          }
          if ($model->save()) {
              return $this->redirect(['index']);
          }
        }

        return $this->render('update', ['model' => $model]);
    }


    /**
     * Delete
     * @param integer $id
     */
     public function actionDelete($id)
     {
         $model = Slider::findOne($id);

        // $id not found in database
        if($model === null)
            throw new NotFoundHttpException('The requested page does not exist.');

        // delete record
        $model->delete();

        return $this->redirect(['index']);
     }


     // public function actionShow($id){
     //
     //
     //    $model =  Slider::find()->where(['QuestionsID' => $id])->one();
     //    $dataProvider = new ActiveDataProvider([
     //        'query' => $query,
     //        'totalCount'=> Reviews::find()->count()
     //    ]);
     //
     //    return $this->render('show',['dataProvider'=>$dataProvider, 'model'=>$model]);
     // }


}

backend/views/slider/_form.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\Edition;
use common\models\Chat;
use backend\models\ReviewAnswers;
use dosamigos\datepicker\DatePicker;
use dosamigos\ckeditor\CKEditor;
use kartik\time\TimePicker;
use frontend\models\User;


/* @var $this yii\web\View */
/* @var $model common\models\Chat */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="chat-form">

    <?php $form = ActiveForm::begin([
        'options' => ['enctype' => 'multipart/form-data'],
    ]); ?>
     <?= $form->field($model, 'slider_1')->fileInput() ?>
     <?= $form->field($model, 'slider_2')->fileInput() ?>
     <?= $form->field($model, 'slider_3')->fileInput() ?>
     <?= $form->field($model, 'slider_4')->fileInput() ?>
     <?= $form->field($model, 'slider_5')->fileInput() ?>
     <?= $form->field($model, 'slider_6')->fileInput() ?>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/slider/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\ChatSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="chat-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'ID') ?>

    <?= $form->field($model, 'Edition') ?>

    <?= $form->field($model, 'ChatDate') ?>

    <?= $form->field($model, 'StartTime') ?>

    <?= $form->field($model, 'EndTime') ?>

    <?php // echo $form->field($model, 'Topic') ?>

    <?php // echo $form->field($model, 'Host') ?>

    <?php // echo $form->field($model, 'Description') ?>

    <?php // echo $form->field($model, 'Status') ?>

    <?php // echo $form->field($model, 'Log') ?>

    <?php // echo $form->field($model, 'Podcast') ?>

    <?php // echo $form->field($model, 'ParticipantsLimt') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/slider/_show.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
?>
<div class="post">
    <h2><?= Html::encode($model->Question_1) ?></h2>

    <?= HtmlPurifier::process($model->Question_2) ?>    
</div>

backend/views/slider/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Chat */

$this->title = 'Upload Sliders';
$this->params['breadcrumbs'][] = ['label' => 'Slider', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="chat-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/slider/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\Edition;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\ChatSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Top Sliders';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="chat-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Top Sliders', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

      <table border="1" class="table table-striped table-bordered">
    <tr>
        <th>ID</th>
        <th>Slider 1</th>
        <th>Slider 2</th>
        <th>Slider 3</th>
        <th>Slider 4</th>
        <th>Slider 5</th>
        <th>Slider 6</th>
        <th>Actions</th>
    </tr>
    <?php foreach($model as $field){ ?>
    <tr>
        <td><?= $field->id; ?></td>
        <td><?= $field->slider_1?></td>
        <td><?= Html::img('@frontend/web/sliders/'. $field->slider_2) ?></td>
        <td><?= Html::img('@frontend/web/sliders/'. $field->slider_3) ?></td>
        <td><?= Html::img('@frontend/web/sliders/'. $field->slider_4) ?></td>
        <td><?= Html::img('@frontend/web/sliders/'. $field->slider_5) ?></td>
        <td><?= Html::img('@frontend/web/sliders/'. $field->slider_6) ?></td>
        <td><?= Html::a("Edit", ['slider/edit', 'id' => $field->id]); ?> | <?= Html::a("Delete", ['slider/delete', 'id' => $field->id]); ?></td>
    </tr>
    <?php } ?>
</table>
</div>

backend/views/slider/show.php
<?php

use yii\widgets\ListView;
use backend\models\ReviewQuestions;
use backend\models\ReviewAnswers;
use yii\data\ActiveDataProvider;
use kartik\grid\GridView;
use yii\helpers\Html;


 ?>

 <div class="col-lg-12">
<?php
$gridColumns = [
    ['class' => 'kartik\grid\SerialColumn'],
    
     [
        'attribute' => $model->questions->Question_1,
        'value' => function($model) {
                    return $model->Answer_1;
         }
    ],
    [
        'attribute' => $model->questions->Question_2,
        'value' => function($model) {
                    return $model->Answer_2;
         }
    ],
     [
        'attribute' => $model->questions->Question_3,
        'value' => function($model) {
                    if($model->Answer_3 == NULL){
                     return '';
                 }else{
                    return $model->Answer_3;
                }
         }
    ],
    
    [
        'attribute' => $model->questions->Question_4,
        'value' => function($model) {
                     if($model->Answer_4 == NULL){
                     return '';
                 }else{
                    return $model->Answer_4;
                }
         }
    ],
    [
        'attribute' => $model->questions->Question_5,
        'value' => function($model) {
                 if($model->Answer_5 == NULL){
                     return '';
                 }else{
                    return $model->Answer_5;
                }
         }
    ],
    [
        'attribute' => 'Comment',
        'value' => function($model) {
                 if($model->comment == NULL){
                     return '';
                 }else{
                    return $model->comment;
                }
         }
    ],
];
// foreach ($dataProvider->getModels() as $key => $value) {
//     var_dump($value);die;
// }

echo GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => $gridColumns,
    'containerOptions' => ['style'=>'overflow: auto'], // only set when $responsive = false
    'beforeHeader'=>[
        [
            // 'columns'=>[
            //     ['content'=>'Header Before 1', 'options'=>['colspan'=>4, 'class'=>'text-center warning']], 
            //     ['content'=>'Header Before 2', 'options'=>['colspan'=>4, 'class'=>'text-center warning']], 
            //     ['content'=>'Header Before 3', 'options'=>['colspan'=>3, 'class'=>'text-center warning']], 
            // ],
            'options'=>['class'=>'skip-export'] // remove this row from export
        ]
    ],
    'toolbar' =>  [
        // ['content'=>
        //     // Html::button('&lt;i class="glyphicon glyphicon-plus">&lt;/i>', ['type'=>'button', 'title'=>Yii::t('', 'Add Book'), 'class'=>'btn btn-success', 'onclick'=>'alert("This will launch the book creation form.\n\nDisabled for this demo!");']) . ' '.
        //     // Html::a('&lt;i class="glyphicon glyphicon-repeat">&lt;/i>', ['grid-demo'], ['data-pjax'=>0, 'class' => 'btn btn-default', 'title'=>Yii::t('kvgrid', 'Reset Grid')])
        // ],
        '{export}',
        '{toggleData}'
    ],
    // 'pjax' => true,
    // 'bordered' => true,
    // 'striped' => false,
    
    // 'responsive' => true,
    // 'hover' => true,
     //'floatHeader' => true,
    // // 'floatHeaderOptions' => ['scrollingTop' => $scrollingTop],
     'showPageSummary' => true,
     'panel' => [
         'type' => GridView::TYPE_PRIMARY
     ],
]);
?>
</div>

backend/views/slider/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Chat */

$this->title = 'Update Sliders: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Sliders', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="chat-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/slider/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use frontend\models\User;

/* @var $this yii\web\View */
/* @var $model common\models\Chat */

$this->title = $model->ID;
$this->params['breadcrumbs'][] = ['label' => 'Chats', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="chat-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->ID], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->ID], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'ID',
            [                      // the owner name of the model
                'label' => 'Edition',
                'value' => $model->edition->EditionName,
            ],            
            'ChatDate',
            'StartTime',
            'EndTime',
            'Topic',
            [                      // the owner name of the model
                'label' => 'Host',
                'value' => $model->host->CeoString,
            ], 
            'Description:ntext',
            [                      // the owner name of the model
                'label' => 'Status',
                'value' => $model->chatStatus($model->Status),
            ],
            'Log',
            'Podcast',
            'ParticipantsLimt',

            
        ],
    ]) ?>

</div>